server:
  port: 8761
spring:
  freemarker:
    template-loader-path: classpath:/templates/
    prefer-file-system-access: false

  server:
    port: 8761

eureka:
  instance:
    preferIpAddress: true
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/