resilience4j.ratelimiter:
  instances:
    throttledOp:
      limitForPeriod: 5
      limitRefreshPeriod: 1s
      timeoutDuration: 0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/